version: 2

models:
  - name: stg_transactions
    description: "Staged transactions from silver layer"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: type
        description: "Transaction type"
        tests:
          - accepted_values:
              values: ["CASH_IN", "CASH_OUT", "DEBIT", "PAYMENT", "TRANSFER"]
      - name: amount
        description: "Transaction amount"
        tests:
          - not_null
      - name: is_fraud
        description: "Fraud label"
        tests:
          - not_null
